# Generated by Django 3.1.2 on 2021-02-04 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_auto_20210204_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='documents/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.lecturer')),
            ],
        ),
    ]
