# Generated by Django 3.1.2 on 2021-02-04 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='pdf',
            new_name='doc',
        ),
        migrations.RemoveField(
            model_name='document',
            name='doc_name',
        ),
    ]
