# Generated by Django 3.1.2 on 2021-02-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0002_auto_20210205_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc',
            field=models.FileField(max_length=1000, upload_to='documents/'),
        ),
    ]
