# Generated by Django 3.1.2 on 2021-01-22 14:14

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailactivation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='department',
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='EmailActivation',
        ),
    ]
