# Generated by Django 3.1.6 on 2021-02-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210123_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofilepicture',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
