# Generated by Django 3.1.2 on 2021-02-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210204_1110'),
        ('accounts', '0005_auto_20210204_1722'),
    ]

    operations = [
    ]
